import type { Metadata } from "next";
import { Hind, Montserrat } from "next/font/google"
import Favicon from "@/public/favicon.ico";
import "./globals.css";
import Navbar from "./components/navbar";

const hind = Hind({
  subsets:["latin"],
  variable: "--font-body",
  weight: "400",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-title",
  weight: "800",
});

export const metadata: Metadata = {
  title: "Encanto das Mãos",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${hind.variable} ${montserrat.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
